name: Test on secondary OSes (Windows, Mac)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Use Node.js 14
      uses: actions/setup-node@v2
      with:
        node-version: 14.x
        cache: 'npm'
    - name: Install dependencies
      run: |
        npm install typescript vsce
        npm ci
    - name: Package
      run: vsce package
    - name: Test
      run: npm test
    - name: UI Test
      run: npm run ui-test     
