version: 2.1

job_default: &job_defaults
  working_directory: ~/vscode-atlasmap
  docker:
    - image: cimg/node:16.15-browsers
  
jobs:
  build:
    <<: *job_defaults
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: install-typescript
          command: npm install --prefix=$HOME/.local -g typescript
      - run:
          name: install-vsce
          command: npm install --prefix=$HOME/.local -g vsce
      - run:
          name: npm-ci
          command: npm ci
      - run:
          name: npm-vscode:prepublish
          command: npm run vscode:prepublish
      - run:
          name: vsce-package
          command: vsce package
      - run:
          name: test
          command: npm test
      - run:
          name: test UI
          command: npm run ui-test
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ~/.npm
      - store_artifacts:
          path: ~/.config/Code/logs
          name: Store VS Code logs
      - store_artifacts:
          path: ~/.config/Code/User/workspaceStorage/
          name: Store VS Code User Workspace storage
      - store_artifacts:
          path: ~/vscode-atlasmap/test-resources/screenshots
          name: Store VS Code UI Tests screenshots on failure
      - when:
          condition:
            equal: [main, << pipeline.git.branch >>]
          steps:
            - sonarcloud/scan

orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.2

workflows:
  version: 2
  vscode-atlasmap:
    jobs:
      - build:
          context: sonarcloud
