name: Test on secondary OSes

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2
    - run: |
        wget -O ${{ runner.temp }}/java_package.zip https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.9.1%2B1/OpenJDK11U-jdk_x64_windows_hotspot_11.0.9.1_1.zip
      if: ${{ runner.os == 'Windows'}}
    - run: |
        download_url="https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.9.1%2B1/OpenJDK11U-jre_x64_mac_hotspot_11.0.9.1_1.tar.gz"
        wget -O $RUNNER_TEMP/java_package.tar.gz $download_url
      if: ${{ runner.os == 'MacOS'}}
    - uses: actions/setup-java@v3
      with:
       distribution: 'jdkfile'
       jdkFile: ${{ runner.temp }}/java_package.zip
       java-version: '11.0.0'
       architecture: x64
      if: ${{ runner.os == 'Windows'}}
    - uses: actions/setup-java@v3
      with:
       distribution: 'jdkfile'
       jdkFile: ${{ runner.temp }}/java_package.tar.gz
       java-version: '11.0.0'
       architecture: x64
      if: ${{ runner.os == 'MacOS'}}
    - name: Use Node.js 14
      uses: actions/setup-node@v2
      with:
        node-version: 14.x
        cache: 'npm'
    - name: Install typescript
      run: npm install -g typescript
    - name: Install vsce
      run: npm install -g vsce
    - name: Install dependencies
      run: npm ci
    - name: Package
      run: vsce package
    - name: Test
      run: npm test
    - name: UI Test
      run: npm run ui-test
    - name: Store VS Code logs
      uses: actions/upload-artifact@v2
      if: always()
      with:
        name: vscode-logs-${{ matrix.os }}
        path: test-resources/settings/logs
    - name: Store VS Code UI Tests screenshots on failure
      uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: ui-test-screenshots-${{ matrix.os }}
        path: test-resources/screenshots
