name: Test on secondary OSes

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-12, windows-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: 11
        distribution: temurin
    - name: Use Node.js 16
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: 'npm'
    - name: Install typescript
      run: npm install -g typescript
    - name: Install vsce
      run: npm install -g vsce
    - name: Install dependencies
      run: npm ci
    - name: Package
      run: vsce package
    - name: Test
      run: npm test
    - name: UI Test
      run: npm run ui-test
    - name: Store VS Code logs
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: vscode-logs-${{ matrix.os }}
        path: uitest-resources/settings/logs
    - name: Store VS Code UI Tests screenshots on failure
      uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: ui-test-screenshots-${{ matrix.os }}
        path: uitest-resources/screenshots
